style = "sciml"
yas_style_nesting = true
always_for_in = true
annotate_untyped_fields_with_any = true
# for_in_replacement = true
format_docstrings = true
indent_submodule = true
join_lines_based_on_source = true
long_to_short_function_def = true
normalize_line_endings = "unix"
remove_extra_newlines = true
short_to_long_function_def = true
whitespace_typedefs = true
