# Constants
const CONFIG_FILE = "data/config.yaml"
const CHECKMARK = " ✓"
const MISSING_VALUE_FILLER = missing
const COMMON_ITEMS_MATRIX_TITLE = "\nCommon Items Matrix:"
const OPTIMIZATION_RESULTS_TITLE = "\nOptimization Results:"
const OPTIMIZATION_FAILED_MESSAGE = "Optimization failed"
const LOADING_CONFIGURATION_MESSAGE = "Loading configuration..."
const RUNNING_OPTIMIZATION_MESSAGE = "Running optimization..."
const FORMS_ASSEMBLED_MESSAGE = "Total forms assembled: "
const ITEMS_USED_MESSAGE = "Items used (includes anchor): "
const ANCHOR_USED_MESSAGE = "Anchor items used: "
const NONANCHOR_USED_MESSAGE = "Non-anchor items used: "
const REMAINING_ITEMS_MESSAGE = "Items not used (without anchor): "
const TOLERANCE_LABEL = "Value: "
const SEPARATOR = "====================================="
const SAVE_FILE_NAME = "data/forms.csv"
